### ISSUE TITLE
Open https://reddit.com links inside the app

### ISSUE THREAD

**Issue by olivertzeng** [alizahid/acorn#10]
Like Apollo where clicking links in the app redirects you to itself

**Comment by alizahid** [comment]
Most links to posts, communities, users, etc, already open within Acorn. Including Reddit magic shortcut links.

The ones that don't are the ones I haven't built any functionality to handle. Eg, wikis.

**Comment by olivertzeng** [comment]
> Most links to posts, communities, users, etc, already open within Acorn. Including Reddit magic shortcut links.
> 
> The ones that don't are the ones I haven't built any functionality to handle. Eg, wikis.

oops mb for not noticing it work
