### ISSUE TITLE
Add iOS backdrop blur on bottom/top bars as an option

### ISSUE THREAD

**Issue by gazecube** [alizahid/acorn#5]
This is a pretty weird nitpick, but I feel that this app feels slightly out of place on iOS since it lacks the dynamic blur iOS uses on its’ toolbars. Winston is a great example of how to use dynamic blur properly; It looks like it could’ve been made by Apple themselves, and while this app’s UI looks great, the lack of dynamic blur just kills the experience for me. It’s small but it’s just enough for me to use alternatives. If you could add some backdrop blur to the toolbars, I would start using this so fast it’d make Sonic the Hedgehog look like a Toyota Prius.

**Comment by alizahid** [comment]
You're not gonna believe this. I'm working on that this week!

**Comment by gazecube** [comment]
I see the blur and it’s looking nice so far, HOWEVER, the white overlay isn’t there yet and messes with the readability of things a tad, which is most noticeable when scrolling on dark backgrounds when using light mode. 
How Acorn handles blur currently:
![IMG_0798](https://github.com/user-attachments/assets/b88a540f-88a3-41c1-aeba-031370193857)
How Apollo handles blur:
![IMG_0797](https://github.com/user-attachments/assets/14d668d6-73e6-4887-8e11-720747a22043)

In addition to the tinted blur, iOS also has a small grey border on the edge of toolbars, which helps the toolbar not blend into the background. 
Example taken from Apollo:
![IMG_0799](https://github.com/user-attachments/assets/1bc2df80-1476-44cd-bf0b-24ec1b7d6834)

**Comment by alizahid** [comment]
I've fixed this. Will release it soon!

**Comment by alizahid** [comment]
@gazecube Check out build 34.
