### ISSUE TITLE
Highlight upvoted comment or resize the scale of the arrows

### ISSUE THREAD

**Issue by olivertzeng** [alizahid/acorn#6]
![image](https://github.com/user-attachments/assets/d5f072b7-a2f7-4311-8a20-cdeb2810359a)
![image](https://github.com/user-attachments/assets/aa3540ee-6594-4ec2-8c52-39b06d9981a4)
Especially comments with images embedded, the upvotes and downvotes buttons aren't that significant to notice as it is a very important element of Reddit. I hope that these buttons will be bigger to see or even highlight with orange/purple when upvoting/downvoting a comment

Kinda more used to Apollo style comments

**Comment by olivertzeng** [comment]
Or at least highlight the upvote count text

**Comment by alizahid** [comment]
This is what I'm going with;

<img width="467" alt="Screenshot 2024-12-08 at 13 42 17" src="https://github.com/user-attachments/assets/1f23d340-be78-4aad-b0aa-05fc02678012">

**Comment by olivertzeng** [comment]
Nice stuff! Will the grean and purple/orange stack if you save the post/comment and vote it as well
 Sent from Proton Mail for iOS 
於 週日, 12月 8, 2024 時間 17:43, Ali Zahid ***@***.***&gt; 寫道：   This is what I'm going with; Screenshot.2024-12-08.at.13.42.17.png (view on web) —

**Comment by alizahid** [comment]
Yes!

<img width="463" alt="Screenshot 2024-12-08 at 14 14 52" src="https://github.com/user-attachments/assets/b46c0f2c-9028-48d8-87c9-9b1ab3043cb9">

**Comment by olivertzeng** [comment]
Oh nice stuff! Thanks bro Sent from Proton Mail for iOS 
於 週日, 12月 8, 2024 時間 18:15, Ali Zahid ***@***.***&gt; 寫道：   Yes! Screenshot.2024-12-08.at.14.14.52.png (view on web) —
