### ISSUE TITLE
"Cancel" button to dismiss the keyboard

### ISSUE THREAD

**Issue by olivertzeng** [alizahid/acorn#7]
![image](https://github.com/user-attachments/assets/be5188bc-235f-4eac-a87f-31f5ecca1707)
![image](https://github.com/user-attachments/assets/7a79cab0-f7b7-4eff-bbc4-2b62d187776c)

**Comment by alizahid** [comment]
You can tap anywhere or start scrolling to dismiss the keyboard.

**Comment by olivertzeng** [comment]
> You can tap anywhere or start scrolling to dismiss the keyboard.

yeah i get it but it just feels kinda "missing"
but i get the point
