### ISSUE TITLE
Make the current subreddit one's in in the middle of the title like Apollo

### ISSUE THREAD

**Issue by olivertzeng** [alizahid/acorn#8]
![image](https://github.com/user-attachments/assets/86bc6284-f855-4038-8c81-2554c88b4a00)
![image](https://github.com/user-attachments/assets/927411f6-4d1f-4007-95b7-95f50dfd43b4)

**Comment by alizahid** [comment]
The name already shows when you navigate to the community.

<img width="511" alt="Screenshot 2024-12-08 at 15 51 16" src="https://github.com/user-attachments/assets/58b1ffc3-fd5f-4da6-a88d-9c76b4859544">

<p/>

Or when you open a post.

<img width="474" alt="Screenshot 2024-12-08 at 15 51 21" src="https://github.com/user-attachments/assets/4b25baf9-01b1-4a75-a65c-a52e793e6851">

<p/>

---

I've changed the home header to show the name.

<img width="502" alt="Screenshot 2024-12-08 at 15 51 31" src="https://github.com/user-attachments/assets/9d2901e8-b0e0-4bcf-b5be-435a80d1b1c1">

**Comment by olivertzeng** [comment]
> The name already shows when you navigate to the community.
> 
> 
> 
> <img width="511" alt="Screenshot 2024-12-08 at 15 51 16" src="https://github.com/user-attachments/assets/58b1ffc3-fd5f-4da6-a88d-9c76b4859544">
> 
> 
> 
> <p/>
> 
> 
> 
> Or when you open a post.
> 
> 
> 
> <img width="474" alt="Screenshot 2024-12-08 at 15 51 21" src="https://github.com/user-attachments/assets/4b25baf9-01b1-4a75-a65c-a52e793e6851">
> 
> 
> 
> <p/>
> 
> 
> 
> ---
> 
> 
> 
> I've changed the home header to show the name.
> 
> 
> 
> <img width="502" alt="Screenshot 2024-12-08 at 15 51 31" src="https://github.com/user-attachments/assets/9d2901e8-b0e0-4bcf-b5be-435a80d1b1c1">

Oh okay but ig I'm more used to having all of them in the middle
